development: &development
     adapter: postgresql
     database: pmailboxd
     username: rails2
     password: rails2
     host:     localhost
     schema_search_path: public
     min_messages: warning

test:
     <<: *development
     database: pmailboxt

production:
     <<: *development
     database: pmailboxp